version: '3.7'

networks:
  devnet:
    external:
      name: development

services:
  boilerplate-dev:
    build:
      context: .
    container_name: birthday-notification
    environment:
      - NODE_ENV=development
      - PORT=4000
      - API_VERSION=1.0
      - JWT_SECRET=D3L9tm42hpMawjP6oUUT
      - UNIQUE_NAME_PG_DB=birthday-notif
      - UNIQUE_NAME_PG_PORT=5432
      - UNIQUE_NAME_PG_HOST=localhost
      - UNIQUE_NAME_PG_USER=postgres
      - UNIQUE_NAME_PG_PASSWD=asdf1234
      - UNIQUE_NAME_PG_SSL=false
      - UNIQUE_NAME_PG_CERT_CA='somethingHere'

    networks:
      - devnet
    restart: unless-stopped